// Generated by CoffeeScript 1.10.0
var Actions, DefaultRoute, NotFoundRoute, RedirectRoute, Route, Store;

Store = {
  count: 0
};

Actions = {
  tick: function() {
    Store.count += 1;
    return this.update({
      count: Store.count
    });
  }
};

Route = riot.router.Route;

DefaultRoute = riot.router.DefaultRoute;

NotFoundRoute = riot.router.NotFoundRoute;

RedirectRoute = riot.router.RedirectRoute;

riot.mount('*');

riot.router.routes([
  new DefaultRoute({
    tag: 'example-cont'
  }), new Route({
    path: '/professionals',
    tag: 'table-users'
  }), new Route({
    path: '/companies',
    tag: 'table-companies'
  }), new Route({
    path: '/universities',
    tag: 'table-unis'
  }), new Route({
    path: '/profile',
    tag: 'profile'
  }), new Route({
    path: '/users/:id',
    tag: 'user'
  }), new NotFoundRoute({
    tag: 'not-found'
  })
]);

riot.router.start();

console.log("Riot started");

Org.all().then(function(orgs) {
  return c.log("Orgs:", orgs);
})["catch"](function(error) {
  return c.error("Error: " + error);
});
