// Generated by CoffeeScript 1.10.0
var PENDING_TXST, socket, updateStatus, updateStatusDebounced, wsHost;

riot.mount('*', {
  store: store
});

riot.router.routes(ROUTES);

riot.router.start();

console.log("Riot started");

updateStatus = function(status) {
  StoreData.evt = status;
  return store.update(StoreData);
};

updateStatusDebounced = _.debounce(updateStatus);

PENDING_TXST = null;

wsHost = "localhost:3001";

if (APP_ENV === "prod") {
  wsHost = bappHost;
}

socket = new WebSocket("ws://" + wsHost);

socket.onopen = function(event) {
  return c.log("PING");
};

socket.onmessage = function(event) {
  var status;
  status = event.data;
  c.log("WS EVENT RECEIVED: " + status);
  if (status) {
    updateStatusDebounced(status);
    if (status === "tx_pending") {
      PENDING_TXST = true;
      _.delay(function() {
        if (PENDING_TXST) {
          return updateStatusDebounced(null);
        }
      }, 10000);
    }
    if (status === "tx_latest") {
      if (PENDING_TXST) {
        updateStatus(status);
      }
      PENDING_TXST = null;
      return _.delay(function() {
        return updateStatusDebounced(null);
      }, 3000);
    }
  }
};
