// Generated by CoffeeScript 1.10.0
var BR;

BR = {
  getEntryId: function() {
    var entry_id;
    entry_id = s(location.hash).strRightBack("/").value();
    return Number(entry_id);
  },
  loadFromCollection: (function(_this) {
    return function(name, entry_id, coll_name, ctx, presenter) {
      var coll, elem;
      coll = StoreData[coll_name];
      elem = _(coll).find(function(e) {
        return entry_id === e.id;
      });
      if (presenter) {
        elem = presenter(elem);
      }
      ctx[name] = elem;
      ctx.update();
      _this.store = ctx.opts.store;
      return _this.store.on('update', function(data) {
        coll = data[coll_name];
        elem = _(coll).find(function(e) {
          return entry_id === e.id;
        });
        if (presenter) {
          elem = presenter(elem);
        }
        ctx[name] = elem;
        return ctx.update();
      });
    };
  })(this)
};
