// Generated by CoffeeScript 1.10.0
var BR;

BR = {
  getEntryId: function() {
    var entry_id;
    entry_id = s(location.hash).strRightBack("/").value();
    return Number(entry_id);
  },
  loadFromCollection: (function(_this) {
    return function(name, entry_id, ctx, presenter) {
      var coll, coll_name, elem;
      coll_name = BR.pluralize(name);
      coll = StoreData[coll_name];
      elem = _(coll).find(function(e) {
        return entry_id === e.id;
      });
      if (presenter) {
        elem = presenter(elem);
      }
      ctx[name] = elem;
      ctx.update();
      _this.store = ctx.opts.store;
      return _this.store.on('update', function(data) {
        coll = data[coll_name];
        elem = _(coll).find(function(e) {
          return entry_id === e.id;
        });
        if (presenter) {
          elem = presenter(elem);
        }
        ctx[name] = elem;
        return ctx.update();
      });
    };
  })(this),
  appendNewObjToColl: (function(_this) {
    return function(obj, coll_name) {
      var coll, last;
      coll = StoreData[coll_name];
      last = _(coll).last();
      coll.push(obj);
      return obj.id = last.id + 1;
    };
  })(this),
  bindSaveEntityForm: (function(_this) {
    return function(action, name, entry_id, ctx) {
      var coll_name, form;
      coll_name = BR.pluralize(name);
      form = "form#" + name + "_form";
      _this.message = "";
      return ctx.on('mount', function(data) {
        var spinner;
        spinner = $(form + " .spinner");
        return $(form + " input[type=submit]").on("click", function(evt) {
          var klass, obj, values;
          spinner.css({
            visibility: "visible"
          });
          obj = ctx[name];
          klass = G[s.capitalize(name)];
          values = $("" + form).serializeArray();
          _(values).each(function(entry) {
            return obj[entry.name] = entry.value;
          });
          c.log(name + "." + action + "()", obj);
          return klass[action](obj).then(function(resp) {
            c.log(name + " updated:", resp);
            spinner.css({
              visibility: "hidden"
            });
            $(form + " .message").html("saved!");
            if (action === "create") {
              return BR.appendNewObjToColl(obj, coll_name);
            }
          })["catch"](function(error) {
            c.error("Error: Cannot " + action + " current " + name + ":", error);
            return c.error(error.stack);
          });
        });
      });
    };
  })(this),
  bindCreateEntityForm: (function(_this) {
    return function(name, ctx) {
      return BR.bindSaveEntityForm("create", name, null, ctx);
    };
  })(this),
  bindUpdateEntityForm: (function(_this) {
    return function(name, entry_id, ctx) {
      return BR.bindSaveEntityForm("update", name, entry_id, ctx);
    };
  })(this),
  pluralize: function(word) {
    if (s(word).endsWith('y')) {
      word = word.substring(word.length - 1);
      return word + "ies";
    } else {
      return word + "s";
    }
  }
};
