// Generated by CoffeeScript 1.11.1
var presentOrg, presentUser;

presentOrg = function(org) {
  if (org && org.publicKey) {
    org.publicKeyShort = org.publicKey.slice(0, 9) + "..." + org.publicKey.slice(-6);
  }
  return org;
};

presentUser = function(user) {
  if (user && user.publicKey) {
    user.publicKeyShort = user.publicKey.slice(0, 9) + "..." + user.publicKey.slice(-6);
  }
  return user;
};
