// Generated by CoffeeScript 1.10.0
var Companies, Unis, Users;

Users = [
  {
    id: 1,
    name: "Stephanie Curry",
    avatar: "http://api.randomuser.me/portraits/thumb/women/0.jpg",
    avatarLg: "http://api.randomuser.me/portraits/med/women/0.jpg",
    jobTitle: "Software Developer"
  }, {
    id: 2,
    name: "Klay Thompson",
    avatar: "http://api.randomuser.me/portraits/thumb/men/3.jpg",
    avatarLg: "http://api.randomuser.me/portraits/med/men/3.jpg",
    jobTitle: "Graphic Designer"
  }, {
    id: 3,
    name: "Catherine Thompson",
    avatar: "http://api.randomuser.me/portraits/thumb/women/2.jpg",
    avatarLg: "http://api.randomuser.me/portraits/med/women/2.jpg",
    jobTitle: "Engineer"
  }, {
    id: 4,
    name: "Garret Albert",
    avatar: "http://api.randomuser.me/portraits/thumb/men/1.jpg",
    avatarLg: "http://api.randomuser.me/portraits/med/men/1.jpg",
    jobTitle: "Mathematician"
  }, {
    id: 5,
    name: "Carla Farad",
    avatar: "http://api.randomuser.me/portraits/thumb/women/4.jpg",
    avatarLg: "http://api.randomuser.me/portraits/med/women/4.jpg",
    jobTitle: "Biologist"
  }
];

Companies = [];

Unis = [];
