// Generated by CoffeeScript 1.10.0
var BApi, G, c;

c = console || {
  log: function() {}
};

G = window;

BApi = (function() {
  function BApi(host) {
    this.host = host;
    this.host = "http://" + this.host;
    this.root = this.host + "/api";
  }

  BApi.prototype.methodGet = function(contractName, name, values) {
    var query;
    query = "";
    if (values != null) {
      query = $.param(values);
    }
    return this.root + "/" + contractName + "/" + name + "?" + query;
  };

  BApi.prototype.get = function(contract, methodName, values) {
    return new Promise((function(_this) {
      return function(resolve, reject) {
        c.log(methodName + "(" + (JSON.stringify(values)) + ") called!");
        return $.getJSON(_this.methodGet(contract, methodName, values)).fail(reject).then(function(val) {
          console.log("GET { contract: " + contract + ", methodName: " + methodName + ", values: " + values + " } ( GET /contract/:contractId/:method?:PARAMS(:values)) })");
          return resolve(val.value);
        });
      };
    })(this));
  };

  return BApi;

})();
