// Generated by CoffeeScript 1.10.0
var API, bappHost, host;

host = document.location.hostname;

bappHost = host === "localhost" ? "localhost:3001" : "api." + host;

host = bappHost;

API = new BApi(host);
