// Generated by CoffeeScript 1.11.1
var Empl, Org, User,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

User = (function(superClass) {
  extend(User, superClass);

  function User(arg) {
    this.id = arg.id, this.name = arg.name, this.publicKey = arg.publicKey, this.location = arg.location, this.achievements = arg.achievements, this.birthDate = arg.birthDate, this.gender = arg.gender, this.nationality = arg.nationality, this.skills = arg.skills;
  }

  User.attrs = ["id", "name", "publicKey", "location", "achievements", "birthDate", "gender", "nationality", "skills"];

  User.prototype.empls = function() {
    var employments;
    employments = _(StoreData.empls).select((function(_this) {
      return function(empl) {
        return empl.userId === _this.id;
      };
    })(this));
    return employments.reverse();
  };

  User.prototype.jobTitle = function() {
    var empl;
    empl = this.empls()[0];
    if (!empl) {
      return "Employee";
    }
    return empl.role;
  };

  return User;

})(BAppModel);

Org = (function(superClass) {
  extend(Org, superClass);

  function Org(arg) {
    this.id = arg.id, this.name = arg.name, this.publicKey = arg.publicKey, this.orgType = arg.orgType, this.location = arg.location, this.industry = arg.industry;
  }

  Org.attrs = ["id", "name", "publicKey", "orgType", "location", "industry"];

  return Org;

})(BAppModel);

Empl = (function(superClass) {
  extend(Empl, superClass);

  function Empl(arg) {
    this.id = arg.id, this.userId = arg.userId, this.orgId = arg.orgId, this.dateStart = arg.dateStart, this.dateEnd = arg.dateEnd, this.role = arg.role, this.reportsTo = arg.reportsTo, this.budget = arg.budget, this.desc = arg.desc, this.approved = arg.approved, this.approvedAt = arg.approvedAt;
  }

  Empl.collectionUp = function() {
    return "Employments";
  };

  Empl.attrs = ["id", "userId", "orgId", "dateStart", "dateEnd", "role", "reportsTo", "budget", "desc", "approved", "approvedAt"];

  Empl.attrsSave = ["id", "userId", "orgId", "dateStart", "dateEnd", "role", "reportsTo", "budget", "desc"];

  Empl.prototype.dateLocale = function(date) {
    if (isNaN(date)) {
      return null;
    }
    return date.toLocaleDateString();
  };

  Empl.prototype.dateStartLoc = function() {
    return this.dateLocale(new Date(this.dateStart));
  };

  Empl.prototype.dateEndLoc = function() {
    return this.dateLocale(new Date(this.dateEnd));
  };

  Empl.prototype.dateRange = function() {
    return "from " + (this.dateStartLoc() || "unknown") + " to " + (this.dateEndLoc() || "present");
  };

  Empl.prototype.approvedAtString = function() {
    var date;
    date = new Date(this.approvedAt);
    return "approved on " + (date.toLocaleDateString());
  };

  Empl.approve = function(id) {
    var now;
    now = new Date().toISOString();
    return API.post(this.collection(), "approve", {
      id: id,
      _approvedAt: now
    });
  };

  return Empl;

})(BAppModel);
