// Generated by CoffeeScript 1.10.0
var BAppModel;

BAppModel = (function() {
  function BAppModel() {}

  BAppModel.prototype.modelName = function() {
    this.c = console;
    return this.constructor.name;
  };

  BAppModel.prototype.hasAttribute = function(attr) {
    return _(this.attrs).include(attr);
  };

  BAppModel.klass = function() {
    return G[this.name];
  };

  BAppModel["new"] = function(args) {
    return new G[this.name](args);
  };

  BAppModel.collectionUp = function() {
    return this.pluralize(this.name);
  };

  BAppModel.collection = function() {
    return this.collectionUp().toLowerCase();
  };

  BAppModel.get = function(id) {
    if (!API) {
      this.c.error(this.errApiNotFound);
    }
    return API.get(this.collection(), "get", {
      id: id
    }).then((function(_this) {
      return function(values) {
        return _this["new"](values);
      };
    })(this))["catch"](function(error) {
      c.error("Error: " + error);
      return reject(error);
    });
  };

  BAppModel.all = function() {
    return new Promise((function(_this) {
      return function(resolve, reject) {
        return API.get(_this.collection(), "get" + (_this.collectionUp()) + "Count").then(function(count) {
          var promises;
          promises = _this.allGet(count);
          return _this.allResolve(promises, resolve, reject);
        })["catch"](function(error) {
          c.error("Error: " + error);
          return reject(error);
        });
      };
    })(this));
  };

  BAppModel.create = function(values) {
    return new Promise((function(_this) {
      return function(resolve, reject) {
        if (!API) {
          _this.c.error(_this.errApiNotFound);
        }
        values = _this.filterValues(values, _this);
        values = _this.convertValuesForSave(values);
        delete values.id;
        return API.post(_this.collection(), "create", values).then(function(resp) {
          return resolve(resp);
        })["catch"](function(error) {
          c.error("Error: " + error);
          return reject(error);
        });
      };
    })(this));
  };

  BAppModel.update = function(values) {
    return new Promise((function(_this) {
      return function(resolve, reject) {
        if (!API) {
          _this.c.error(_this.errApiNotFound);
        }
        values = _this.filterValues(values, _this);
        values = _this.convertValuesForSave(values);
        return API.post(_this.collection(), "update", values).then(function(resp) {
          return resolve(resp);
        })["catch"](function(error) {
          c.error("Error: " + error);
          return reject(error);
        });
      };
    })(this));
  };

  BAppModel.filterValues = function(values, ctx) {
    var newVals;
    newVals = {};
    _(ctx.attrs).each(function(attr) {
      var val;
      if (_(ctx.attrs).include(attr)) {
        val = values[attr];
      }
      if (!val) {
        val = "-";
      }
      return newVals[attr] = val;
    });
    return newVals;
  };

  BAppModel.convertValuesForSave = function(values) {
    var newVals;
    newVals = {};
    _(values).map(function(value, key) {
      if (key === "id") {
        return newVals[key] = value;
      } else {
        return newVals["_" + key] = value;
      }
    });
    return newVals;
  };

  BAppModel.count = function() {
    return new Promise((function(_this) {
      return function(resolve, reject) {
        return API.get(_this.collection(), "get" + (_this.collectionUp()) + "Count").then(resolve)["catch"](function(error) {
          c.error("Error: " + error);
          return reject(error);
        });
      };
    })(this));
  };

  BAppModel.pluralize = function(word) {
    if (s(word).endsWith('y')) {
      word = word.substring(word.length - 1);
      return word + "ies";
    } else {
      return word + "s";
    }
  };

  BAppModel.allGet = function(count) {
    var i, id, promises, ref;
    promises = [];
    if (count > 0) {
      for (id = i = 1, ref = count; 1 <= ref ? i <= ref : i >= ref; id = 1 <= ref ? ++i : --i) {
        promises.push(API.get(this.collection(), "get", {
          id: id
        }));
      }
    }
    return promises;
  };

  BAppModel.allResolve = function(promises, resolve, reject) {
    return Promise.all(promises).then((function(_this) {
      return function(collectionResp) {
        var collection, i, len, values;
        collection = [];
        for (i = 0, len = collectionResp.length; i < len; i++) {
          values = collectionResp[i];
          collection.push(_this["new"](values));
        }
        return resolve(collection);
      };
    })(this))["catch"](function(error) {
      c.error("Error: " + error);
      return reject(error);
    });
  };

  BAppModel.prototype.errApiNotFound = "API not found, please instantiate it via: 'var API = new BApi(host)'";

  return BAppModel;

})();
