// Generated by CoffeeScript 1.10.0
var BAppModel;

BAppModel = (function() {
  function BAppModel() {}

  BAppModel.prototype.modelName = function() {
    return this.constructor.name;
  };

  BAppModel["new"] = function(args) {
    return new G[this.name](args);
  };

  BAppModel.all = function() {
    var a;
    a = this["new"]({
      id: 1
    });
    return a;
  };

  BAppModel.get = function() {};

  BAppModel.create = function() {};

  BAppModel.update = function() {};

  return BAppModel;

})();
